import { Inter } from "@next/font/google";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <nav>
          <img />
          <a href="/">Home</a>
          <a href="/events">Events</a>
          <a href="/about-us">About Us</a>
        </nav>
      </header>

      <main className={styles.main}>
        <a href="">
          <img />
          <h2>Events in London</h2>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec
            egestas imperdiet elit ac tempor. Phasellus nec dolor porttitor,
            bibendum lorem nec, scelerisque dui.
          </p>
        </a>
        <a href="">
          <img />
          <h2>Events in San Francisco</h2>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec
            egestas imperdiet elit ac tempor. Phasellus nec dolor porttitor,
            bibendum lorem nec, scelerisque dui.
          </p>
        </a>
        <a href="">
          <img />
          <h2>Events in Barcellona</h2>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec
            egestas imperdiet elit ac tempor. Phasellus nec dolor porttitor,
            bibendum lorem nec, scelerisque dui.
          </p>
        </a>
      </main>
      <footer>
        <p> 2022 Time to code - A project Next.js</p>
      </footer>
    </>
  );
}
